const SupportCode = require('../../../common/support-code');

module.exports = {
	'0000': new SupportCode('MY_SUCCESS', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0001': new SupportCode('MAIL_ADDRESS_NOT_CONFIRMED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0500': new SupportCode('LIBRARY_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0501': new SupportCode('NOT_INITIALIZED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0502': new SupportCode('ALREADY_INITIALIZED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0511': new SupportCode('BUSY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0591': new SupportCode('NOT_IMPLEMENTED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0592': new SupportCode('DEPRECATED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0593': new SupportCode('DEVELOPMENT_ONLY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0600': new SupportCode('INVALID_ARGUMENT', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0601': new SupportCode('INVALID_POINTER', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0602': new SupportCode('OUT_OF_RANGE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0603': new SupportCode('INVALID_SIZE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0604': new SupportCode('INVALID_FORMAT', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0605': new SupportCode('INVALID_HANDLE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0606': new SupportCode('INVALID_VALUE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0700': new SupportCode('INTERNAL_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0701': new SupportCode('END_OF_STREAM', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0710': new SupportCode('FILE_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0711': new SupportCode('FILE_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0712': new SupportCode('FILE_VERSION_MISMATCH', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0713': new SupportCode('FILE_IO_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0714': new SupportCode('FILE_TYPE_MISMATCH', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0730': new SupportCode('OUT_OF_RESOURCE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0731': new SupportCode('SHORT_OF_BUFFER', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0740': new SupportCode('OUT_OF_MEMORY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'0741': new SupportCode('OUT_OF_GLOBAL_HEAP', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1000': new SupportCode('ACCOUNT_MANAGEMENT_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1001': new SupportCode('ACCOUNT_NOT_FOUND', 'Missing description', 'Unable to find the specified user.', 'Missing fix', 'Missing link'),
	'1002': new SupportCode('SLOTS_FULL', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1011': new SupportCode('ACCOUNT_NOT_LOADED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1012': new SupportCode('ACCOUNT_ALREADY_LOADED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1013': new SupportCode('ACCOUNT_LOCKED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'1021': new SupportCode('NOT_NETWORK_ACCOUNT', 'Missing description', 'There is no Nintendo Network ID\nlinked to this system.\n\nTo link a Nintendo Network ID, go\nto Nintendo Network ID Settings in\nSystem Settings', 'Missing fix', 'Missing link'),
	'1022': new SupportCode('NOT_LOCAL_ACCOUNT', 'Missing description', 'There is a Nintendo Network ID\nlinked to this system', 'Missing fix', 'Missing link'),
	'1023': new SupportCode('ACCOUNT_NOT_COMMITTED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2000': new SupportCode('AUTHENTICATION_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2100': new SupportCode('HTTP_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2400': new SupportCode('REQUEST_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2401': new SupportCode('BAD_FORMAT_PARAMETER', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2402': new SupportCode('BAD_FORMAT_REQUEST', 'The HTTP request contained invalid data', 'Missing message', 'Try again later or try a different input', 'Missing link'),
	'2403': new SupportCode('REQUEST_PARAMETER_MISSING', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2404': new SupportCode('WRONG_HTTP_METHOD', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2420': new SupportCode('RESPONSE_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2421': new SupportCode('BAD_FORMAT_RESPONSE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2422': new SupportCode('RESPONSE_ITEM_MISSING', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2423': new SupportCode('RESPONSE_TOO_LARGE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2450': new SupportCode('INVALID_COMMON_PARAMETER', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2451': new SupportCode('INVALID_PLATFORM_ID', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2452': new SupportCode('UNAUTHORIZED_DEVICE', 'The device you are using was not authorized to make the request', 'Missing message', 'Try again later or on a different device', 'Missing link'),
	'2453': new SupportCode('INVALID_SERIAL_ID', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2454': new SupportCode('INVALID_MAC_ADDRESS', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2455': new SupportCode('INVALID_REGION', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2456': new SupportCode('INVALID_COUNTRY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2457': new SupportCode('INVALID_LANGUAGE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2458': new SupportCode('UNAUTHORIZED_CLIENT', 'The HTTP client was not authorized to make the request', 'Missing message', 'Try again later or on a different device', 'Missing link'),
	'2459': new SupportCode('DEVICE_ID_EMPTY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2460': new SupportCode('SERIAL_ID_EMPTY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2461': new SupportCode('PLATFORM_ID_EMPTY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2471': new SupportCode('INVALID_UNIQUE_ID', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2472': new SupportCode('INVALID_CLIENT_ID', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2473': new SupportCode('INVALID_CLIENT_KEY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2481': new SupportCode('INVALID_NEX_CLIENT_ID', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2482': new SupportCode('INVALID_GAME_SERVER_ID', 'The game server requested could not be found. Either the game is not supported or is tester-only', 'Missing message', 'Check to see if your game is supported at https://pretendo.network/progress. If you\'re a tester, check your account is set to Beta at https://pretendo.network/account', 'Missing link'),
	'2483': new SupportCode('GAME_SERVER_ID_ENVIRONMENT_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2484': new SupportCode('GAME_SERVER_ID_UNIQUE_ID_NOT_LINKED', 'The game server ID and title ID were not linked, or the request did not send a game server ID. This error should never happen normally', 'Missing message', 'File a bug report with as much detail as possible at https://github.com/PretendoNetwork/account/issues/new', 'Missing link'),
	'2485': new SupportCode('CLIENT_ID_UNIQUE_ID_NOT_LINKED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2501': new SupportCode('DEVICE_MISMATCH', 'The console certificate sent in the request was invalid or missing', 'You cannot use this Nintendo Network\nID on this system.\n\nPlease make a note of the error code\nand visit support.nintendo.com', 'Ensure your console certificate is untampered with and try again later. If using Citra, dump your system files again', 'Missing link'),
	'2502': new SupportCode('COUNTRY_MISMATCH', 'Missing description', 'This Nintendo Network ID cannot be\nused because its region setting does\nnot match the setting of this system.\n\nPlease check Region Settings in System\nSettings ⇒ Other Settings ⇒ Profile, and\nconfirm that this setting matches the ID', 'Missing fix', 'Missing link'),
	'2503': new SupportCode('EULA_NOT_ACCEPTED', 'Missing description', 'To use online services, you must\naccept the terms of the Network\nServices Agreement.\n\nSelect Nintendo Network ID Settings\nin System Settings, and agree to the\nterms', 'Missing fix', 'Missing link'),
	'2510': new SupportCode('UPDATE_REQUIRED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2511': new SupportCode('SYSTEM_UPDATE_REQUIRED', 'Your console is not up to date', 'In order to use online services, a\nsystem update is required.\n\nGo to System Settings to perform a\nsystem update.', 'Update your console', 'Missing link'),
	'2512': new SupportCode('APPLICATION_UPDATE_REQUIRED', 'Your game is not up to date', 'This software must be updated before\nonline services can be used.\n\nTo update the software, download the\nlatest version from Nintendo eShop', 'Update your game', 'Missing link'),
	'2520': new SupportCode('UNAUTHORIZED_REQUEST', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2522': new SupportCode('REQUEST_FORBIDDEN', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2530': new SupportCode('RESOURCE_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2531': new SupportCode('PID_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2532': new SupportCode('NEX_ACCOUNT_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2533': new SupportCode('GENERATE_TOKEN_FAILURE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2534': new SupportCode('REQUEST_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2535': new SupportCode('MASTER_PIN_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2536': new SupportCode('MAIL_TEXT_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2537': new SupportCode('SEND_MAIL_FAILURE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2538': new SupportCode('APPROVAL_ID_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2540': new SupportCode('INVALID_EULA_PARAMETER', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2541': new SupportCode('INVALID_EULA_COUNTRY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2542': new SupportCode('INVALID_EULA_COUNTRY_AND_VERSION', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2543': new SupportCode('EULA_NOT_FOUND', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2570': new SupportCode('PHRASE_NOT_ACCEPTABLE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2571': new SupportCode('ACCOUNT_ID_ALREADY_EXISTS', 'You are trying to create a PNID using a username that is either already in use by another Pretendo user, or is used by a different NNID on your console', 'The Nintendo Network ID you\nentered is already in use.\n\nPlease try again', 'Choose a different username', 'Missing link'),
	'2572': new SupportCode('ACCOUNT_ID_NOT_ACCEPTABLE', 'The Nintendo Network ID you entered\nincludes text that cannot be used.\n\nPlease try again', 'Choose a different username', 'Missing link'),
	'2573': new SupportCode('ACCOUNT_PASSWORD_NOT_ACCEPTABLE', 'The password entered did not follow the instructions', 'The password you entered\ncannot be used.\n\nPlease try again', 'Choose a different password', 'Missing link'),
	'2574': new SupportCode('MII_NAME_NOT_ACCEPTABLE', 'The Mii nickname you entered contains rejected text', 'The nickname you entered\ncannot be used', 'Choose a different nickname', 'Missing link'),
	'2575': new SupportCode('MAIL_ADDRESS_NOT_ACCEPTABLE', 'Invalid email address entered', 'The e-mail address you entered\nis not correct.\n\nPlease check the e-mail address\nyou entered and try again', 'Enter a valid email address', 'Missing link'),
	'2576': new SupportCode('ACCOUNT_ID_FORMAT_INVALID', 'Missing description', 'The Nintendo Network ID you\nentered cannot be used.\n\nPlease try again', 'Missing fix', 'Missing link'),
	'2577': new SupportCode('ACCOUNT_ID_PASSWORD_SAME', 'Your username and password are the same', 'You cannot use a password that is\nidentical to your Nintendo Network ID.\n\nPlease use a different password', 'Change either your username or password', 'Missing link'),
	'2578': new SupportCode('ACCOUNT_ID_CHAR_NOT_ACCEPTABLE', 'Missing description', 'Your entry contains characters\nthat cannot be used.\n\nPlease try again', 'Missing fix', 'Missing link'),
	'2579': new SupportCode('ACCOUNT_ID_SUCCESSIVE_SYMBOL', 'Missing description', 'You can\'t use two or more\npunctuation characters in\na row in your ID.\n\nPlease try again', 'Missing fix', 'Missing link'),
	'2580': new SupportCode('ACCOUNT_ID_SYMBOL_POSITION_NOT_ACCEPTABLE', 'Missing description', 'You can\'t use punctuation\nas the first or last character\nof your ID.\n\nPlease try again', 'Missing fix', 'Missing link'),
	'2581': new SupportCode('ACCOUNT_ID_TOO_MANY_DIGIT', 'Missing description', 'You can\'t use more than six\nnumbers in your ID.\n\nPlease try again', 'Missing fix', 'Missing link'),
	'2582': new SupportCode('ACCOUNT_PASSWORD_CHAR_NOT_ACCEPTABLE', 'Missing description', 'Your entry contains characters\nthat cannot be used.\n\nPlease use a different password', 'Missing fix', 'Missing link'),
	'2583': new SupportCode('ACCOUNT_PASSWORD_TOO_FEW_CHAR_TYPES', 'Missing description', 'Your password must contain characters\nfrom at least two of the following\ncategories: letters, numbers, and\npunctuation.\n\nPlease use a different password', 'Missing fix', 'Missing link'),
	'2584': new SupportCode('ACCOUNT_PASSWORD_SUCCESSIVE_SAME_CHAR', 'Missing description', 'You cannot use the same character\nthree or more times consecutively.\n\nPlease use a different password', 'Missing fix', 'Missing link'),
	'2585': new SupportCode('MAIL_ADDRESS_DOMAIN_NAME_NOT_ACCEPTABLE', 'Missing description', 'The e-mail address you entered cannot\nbe used.\n\nPlease enter a different e-mail address', 'Missing fix', 'Missing link'),
	'2586': new SupportCode('MAIL_ADDRESS_DOMAIN_NAME_NOT_RESOLVED', 'The email address entered uses a domain which could not be located', 'The domain name of the e-mail address\nyou entered may be incorrect.\n\nPlease check the e-mail address you\nentered and try again', 'Enter a different email address', 'Missing link'),
	'2587': new SupportCode('Missing name', 'Missing description', 'The Nintendo Network ID you entered\nalready exists.\n\nIf you want to use this ID, please\nreturn to the beginning of the linking\nprocess, select Link an Existing ID,\nand follow the on-screen instructions.\nYou will need to enter the e-mail\naddress and password used when\nyou initially created the ID', 'Missing fix', 'Missing link'),
	'2591': new SupportCode('REACHED_ASSOCIATION_LIMIT', 'Missing description', 'This Nintendo Network ID has already\nbeen linked to another system in the\nNintendo 3DS family.\n\nPlease select a different Nintendo\nNetwork ID and try again', 'Missing fix', 'Missing link'),
	'2592': new SupportCode('REACHED_REGISTRATION_LIMIT', 'Missing description', 'At the moment, it is not possible to\nlink a Nintendo Network ID to this\nsystem.\n\nYou have reached the limit for ID\nlinking at this time.\n\nPlease try again later', 'Missing fix', 'Missing link'),
	'2593': new SupportCode('COPPA_NOT_ACCEPTED', 'Missing description', 'This Nintendo Network ID cannot be\nused because it has not been confirmed\nby a parent or guardian.\n\nPlease have a parent or guardian\nmake a note of the error code and\nvisit support.nintendo.com', 'Missing fix', 'Missing link'),
	'2594': new SupportCode('PARENTAL_CONTROLS_REQUIRED', 'Missing description', 'Parental Controls restrictions\nmust be set up first', 'Missing fix', 'Missing link'),
	'2595': new SupportCode('MII_NOT_REGISTERED', 'Missing description', 'You have not registered a Mii', 'Missing fix', 'Missing link'),
	'2596': new SupportCode('DEVICE_EULA_COUNTRY_MISMATCH', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2597': new SupportCode('PENDING_MIGRATION', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2610': new SupportCode('WRONG_USER_INPUT', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2611': new SupportCode('WRONG_ACCOUNT_PASSWORD', 'Incorrect password', 'Incorrect password', 'Enter your password again or reset your password and try again', 'Missing link'),
	'2612': new SupportCode('WRONG_MAIL_ADDRESS', 'Missing description', 'The e-mail address you entered is\nnot correct.\n\nPlease check the e-mail address\nyou entered and try again', 'Missing fix', 'Missing link'),
	'2613': new SupportCode('WRONG_ACCOUNT_PASSWORD_OR_MAIL_ADDRESS', 'Invalid account information provided. Either your username, password, or email address does not match', 'The information entered is not correct.\nYou may have entered a Club Nintendo\naccount ID or the ID of another service.\n\nPlease enter the details again, making\nsure that the Nintendo Network ID,\npassword, and e-mail address are\ncorrect', 'Enter corrected information and try again', 'Missing link'),
	'2614': new SupportCode('WRONG_CONFIRMATION_CODE', 'The email confirmation code entered does not match your account', 'Missing message', 'Check your confirmation code and try again', 'Missing link'),
	'2615': new SupportCode('WRONG_BIRTH_DATE_OR_MAIL_ADDRESS', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2616': new SupportCode('WRONG_ACCOUNT_MAIL', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2631': new SupportCode('ACCOUNT_ALREADY_DELETED', 'Missing description', 'You cannot access online services\nbecause the Nintendo Network ID\nformerly linked to this system has\nbeen deleted.\n\nTo create a new ID or link a different\nexisting ID, go to Nintendo Network\nID Settings in System Settings', 'Missing fix', 'Missing link'),
	'2632': new SupportCode('ACCOUNT_ID_CHANGED', 'Missing description', 'Your Nintendo Network ID has changed.\n\nPlease approve the change by selecting\nNintendo Network ID Settings in System\nSettings', 'Missing fix', 'Missing link'),
	'2633': new SupportCode('AUTHENTICATION_LOCKED', 'Missing description', 'This Nintendo Network ID been\ntemporarily locked due to repeated\nincorrect attempts to enter the\npassword.\n\nPlease try again later', 'Missing fix', 'Missing link'),
	'2634': new SupportCode('DEVICE_INACTIVE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2635': new SupportCode('COPPA_AGREEMENT_CANCELED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2636': new SupportCode('DOMAIN_ACCOUNT_ALREADY_EXISTS', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2641': new SupportCode('ACCOUNT_TOKEN_EXPIRED', 'The token provided is expired', 'Missing message', 'Log in again or restart your application or console and try again', 'Missing link'),
	'2642': new SupportCode('INVALID_ACCOUNT_TOKEN', 'The login token provided is invalid', 'Missing message', 'Restart your application or console and try again', 'Missing link'),
	'2643': new SupportCode('AUTHENTICATION_REQUIRED', 'Missing description', 'An error has occurred.\n\nYour session has expired.\nPlease sign in and try again', 'Missing fix', 'Missing link'),
	'2651': new SupportCode('CONFIRMATION_CODE_EXPIRED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2661': new SupportCode('MAIL_ADDRESS_NOT_VALIDATED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2662': new SupportCode('EXCESSIVE_MAIL_SEND_REQUEST', 'Missing description', 'You cannot perform this operation\nseveral times in a row.\n\nPlease try again later', 'Missing fix', 'Missing link'),
	'2670': new SupportCode('CREDIT_CARD_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2671': new SupportCode('CREDIT_CARD_GENERAL_FAILURE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2672': new SupportCode('CREDIT_CARD_DECLINED', 'Missing description', 'The use of this credit card has\nbeen stopped', 'Missing fix', 'Missing link'),
	'2673': new SupportCode('CREDIT_CARD_BLACKLISTED', 'Missing description', 'This credit card cannot be used.\n\nPlease contact your credit-card\nprovider for more information', 'Missing fix', 'Missing link'),
	'2674': new SupportCode('INVALID_CREDIT_CARD_NUMBER', 'Missing description', 'Please check the credit-card\nnumber and try entering it again', 'Missing fix', 'Missing link'),
	'2675': new SupportCode('INVALID_CREDIT_CARD_DATE', 'Missing description', 'Please check the credit-card\nexpiration date and try entering\nit again', 'Missing fix', 'Missing link'),
	'2676': new SupportCode('INVALID_CREDIT_CARD_PIN', 'Missing description', 'Please check the credit-card\nPIN and try entering it again', 'Missing fix', 'Missing link'),
	'2677': new SupportCode('INVALID_POSTAL_CODE', 'Missing description', 'The information entered is not correct.\nPlease check it and try again', 'Missing fix', 'Missing link'),
	'2678': new SupportCode('INVALID_LOCATION', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2679': new SupportCode('CREDIT_CARD_DATE_EXPIRED', 'Missing description', 'The credit card has expired', 'Missing fix', 'Missing link'),
	'2680': new SupportCode('CREDIT_CARD_NUMBER_WRONG', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2681': new SupportCode('CREDIT_CARD_PIN_WRONG', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2800': new SupportCode('BANNED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2801': new SupportCode('BANNED_ACCOUNT', 'Missing description', 'Online services cannot be used', 'Missing fix', 'Missing link'),
	'2802': new SupportCode('BANNED_ACCOUNT_ALL', 'Your PNID is permanently banned from all aspects of the network', 'This Nintendo Network ID\ncannot be used.\n\nPlease make a note of the error code\nand visit support.nintendo.com', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'2803': new SupportCode('BANNED_ACCOUNT_IN_APPLICATION', 'Your PNID is permanently banned from this application', 'Online services cannot be used.\n\nPlease make a note of the error code\nand visit support.nintendo.com', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'2804': new SupportCode('BANNED_ACCOUNT_IN_NEX_SERVICE', 'Your PNID is permanently banned from this game', 'Missing message', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'2805': new SupportCode('BANNED_ACCOUNT_IN_INDEPENDENT_SERVICE', 'Your PNID is permanently banned from this service', 'Missing message', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'2811': new SupportCode('BANNED_DEVICE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2812': new SupportCode('BANNED_DEVICE_ALL', 'Your console is permanently banned from all aspects of the network', 'You cannot access Nintendo Network\nservices using this system. \n\nPlease make a note of the error code\nand visit support.nintendo.com', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'2813': new SupportCode('BANNED_DEVICE_IN_APPLICATION', 'Your console is permanently banned from this application', 'Missing message', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'2814': new SupportCode('BANNED_DEVICE_IN_NEX_SERVICE', 'Your console is permanently banned from this game', 'Missing message', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'2815': new SupportCode('BANNED_DEVICE_IN_INDEPENDENT_SERVICE', 'Your console is permanently banned from this service', 'Missing message', 'Don\'t do whatever you did to get banned', 'Missing link'),
	'2821': new SupportCode('BANNED_ACCOUNT_TEMPORARILY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2822': new SupportCode('BANNED_ACCOUNT_ALL_TEMPORARILY', 'Your PNID is temporarily banned from all aspects of the network', 'Missing message', 'Wait for the ban to expire', 'Missing link'),
	'2823': new SupportCode('BANNED_ACCOUNT_IN_APPLICATION_TEMPORARILY', 'Your PNID is temporarily banned from this application', 'Missing message', 'Wait for the ban to expire', 'Missing link'),
	'2824': new SupportCode('BANNED_ACCOUNT_IN_NEX_SERVICE_TEMPORARILY', 'Your PNID is temporarily banned from this game', 'Missing message', 'Wait for the ban to expire', 'Missing link'),
	'2825': new SupportCode('BANNED_ACCOUNT_IN_INDEPENDENT_SERVICE_TEMPORARILY', 'Your PNID is temporarily banned from this service', 'Missing message', 'Wait for the ban to expire', 'Missing link'),
	'2831': new SupportCode('BANNED_DEVICE_TEMPORARILY', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2832': new SupportCode('BANNED_DEVICE_ALL_TEMPORARILY', 'Your console is temporarily banned from all aspects of the network', 'Missing message', 'Missing fix', 'Wait for the ban to expire'),
	'2833': new SupportCode('BANNED_DEVICE_IN_APPLICATION_TEMPORARILY', 'Your console is temporarily banned from this application', 'Missing message', 'Missing fix', 'Wait for the ban to expire'),
	'2834': new SupportCode('BANNED_DEVICE_IN_NEX_SERVICE_TEMPORARILY', 'Your console is temporarily banned from this game', 'Missing message', 'Missing fix', 'Wait for the ban to expire'),
	'2835': new SupportCode('BANNED_DEVICE_IN_INDEPENDENT_SERVICE_TEMPORARILY', 'Your console is temporarily banned from this service', 'Missing message', 'Missing fix', 'Wait for the ban to expire'),
	'2880': new SupportCode('SERVICE_NOT_PROVIDED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2881': new SupportCode('UNDER_MAINTENANCE', 'The server you requested is under maintenance', 'The server is currently undergoing\nmaintenance. We apologize for any\ninconvenience. Please try again later.\n\nTo learn more about maintenance,\nvisit support.nintendo.com', 'Try again later', 'Missing link'),
	'2882': new SupportCode('SERVICE_CLOSED', 'The server you requested is closed and no longer maintained', 'This online service is no longer\navailable.\n\nSorry for the inconvenience.', 'Self host the server or use another hosted instance', 'Missing link'),
	'2883': new SupportCode('NINTENDO_NETWORK_CLOSED', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2884': new SupportCode('NOT_PROVIDED_COUNTRY', 'Missing description', 'Online services are not available\nin your country of residence', 'Missing fix', 'Missing link'),
	'2900': new SupportCode('RESTRICTION_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2901': new SupportCode('RESTRICTED_BY_AGE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2910': new SupportCode('RESTRICTED_BY_PARENTAL_CONTROLS', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2911': new SupportCode('ON_GAME_INTERNET_COMMUNICATION_RESTRICTED', 'Missing description', 'Online Interaction has been\nrestricted by Parental Controls', 'Missing fix', 'Missing link'),
	'2931': new SupportCode('INTERNAL_SERVER_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2932': new SupportCode('UNKNOWN_SERVER_ERROR', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2998': new SupportCode('UNAUTHENTICATED_AFTER_SALVAGE', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'2999': new SupportCode('AUTHENTICATION_FAILURE_UNKNOWN', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5103': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5104': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5112': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5315': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5350': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5351': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5352': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5360': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5361': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5362': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5363': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5432': new SupportCode('UNKNOWN_ACCOUNT_ERROR', 'An unknown account error has occured', 'Missing message', 'On Nimbus switch to Nintendo and open the eShop. After that switch back to Pretendo and try again. It can be this fix does not work at the first time so if it is not working try again', 'Missing link'),
	'5502': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5503': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5504': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5505': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5506': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5507': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5508': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5509': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5510': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5511': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5512': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5513': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5514': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5515': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5516': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5517': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5518': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5519': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5520': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5521': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5522': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5523': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5524': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5525': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5526': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5527': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5528': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5529': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5530': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5531': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5532': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5533': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5534': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5535': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5536': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5537': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5538': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5539': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5540': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5541': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5542': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5543': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5544': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5545': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5546': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5547': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5548': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5549': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5550': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5551': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5552': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
	'5553': new SupportCode('Missing name', 'Missing description', 'Missing message', 'Missing fix', 'Missing link'),
};
